name: commit_offshore

x-the-logging: &the-logging
  driver: "json-file"
  options:
    max-file: 5
    max-size: 10m

volumes:
  psql_data:
  once_dir:

services:
  if_offshore_db:
    image: postgres:17.3-bookworm
    restart: always
    container_name: cf_offshore_db
    command: postgres -c config_file=/etc/postgresql.conf
    network_mode: host
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./containers/db/psql:/docker-entrypoint-initdb.d/
      - ./containers/db/postgresql.conf:/etc/postgresql.conf
    env_file:
      - .env
    logging: *the-logging

  if_offshore_manager: &if_offshore_manager
    build:
      context: containers
      dockerfile: Dockerfile
    container_name: cf_offshore_manager
    restart: always
    tty: true
    volumes:
      - ./containers/web:/web
      - once_dir:/opt
    env_file:
      - .env
    logging: *the-logging

  if_offshore_web:
    <<: *if_offshore_manager
    restart: always
    container_name: cf_offshore_web
    command: ./booter.sh
    network_mode: host
    env_file:
      - .env
    logging: *the-logging
