name: commit_offshore

x-the-logging: &the-logging
  driver: "json-file"
  options:
    max-file: 5
    max-size: 10m

volumes:
  psql_data:

services:
  if_offshore_db:
    image: postgres:17.3-bookworm
    restart: always
    container_name: cf_offshore_db
    command: ${POSTGRES_COMMAND}
    ports:
      - ${POSTGRES_PORT}:6379
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./containers/db/psql:/docker-entrypoint-initdb.d/
      - ./containers/db/postgresql.conf:/etc/postgresql.conf
    env_file:
      - .env
    logging: *the-logging

  if_offshore_manager: &if_offshore_manager
    build:
      context: containers
      dockerfile: Dockerfile
    container_name: cf_offshore_manager
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./containers/web:/web
    env_file:
      - .env
    logging: *the-logging

  if_offshore_web:
    <<: *if_offshore_manager
    restart: always
    container_name: cf_offshore_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - ${WEB_APP_PORT}:80
    env_file:
      - .env
    logging: *the-logging
